### PR TITLE
Propositions

### PR DESCRIPTION
**Pull request by Karol-2**
I have too much free time, so I added a long-awaited feature - friend suggestions.

Main changes:

- [X] Add Friend suggestions - friends of your friends that aren't your friends.
- [x] Add Paginator - to improve the readability of long lists.
- [X] Move code for displaying friends to a separate component - Friend.
- [X] Add Paginator for different features - for search (5 per page), for suggestions (3 pp) and friend list (5 pp).

suggestion

Created with help of this little fella:

### CODE REVIEW

**Review by gf-rog — APPROVED** [review]
I admire your willpower to start working so quickly.
I've noticed a few typos but I'll let them pass.
Please format the code. I should fix the workflow to automatically format files.
Nice kitty. Mine unfortunately doesn't help me code...
cat

**Comment by gf-rog** [comment]
I forgot to mention - paging should be done in the backend since you shouldn't send a million users every time someone wants to add a friend. I could fix it in the future

**Review by Piterson25 — APPROVED** [review]
It works! 😊
obraz

**Review by JANKROL123 — APPROVED** [review]
Looks so good

**Pull request merged**
