### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by Karol-2**
Feel free to edit, especially video and chat systems. This version is before merging pull requests from 13.01.2024.

### CODE REVIEW

**Review by Piterson25 — APPROVED** [review]
🔥

**Comment by gf-rog** [comment]
The pics folder is not included so I can't see the pictures after building the .pdf file

**Comment by Karol-2** [comment]
> The pics folder is not included so I can't see the pictures after building the .pdf file

Yeah, we work on it on Overleaf, thats why i gave you already generated pdf :).

**Review by gf-rog — APPROVED** [review]

**Review by JANKROL123 — APPROVED** [review]
ok

**Pull request merged**
