### PR TITLE
Add Keycloak

### LINKED ISSUE #31: Keycloak

### PR DESCRIPTION
**Pull request by gf-rog**
Closes #31.
Some things have changed, most notably:

1. Backend user's business logic was moved to `backend/src/users.ts` for better readability and reuse
2. Backend is now an ES module instead of using CommonJS. The most important aspect of this change to keep in mind is that Typescript imports now have to end in `.js`.
3. Keycloak is running in its own container named `keycloak`. It has to be run in development if the user provider in `frontend/main.tsx` is set to `<KeycloakUserProvider>`.
4. Initial users are still registered using the old system (let me know if I should change this). For now a test Keycloak user is created with mail `jsmith@example.com` and password `password`.
5. The protected endpoints are wrapped in a `<Protected>` tag. It automatically redirects if the user is not logged in and allows for easy access of the logged in user without checking whether it's null first (`useProtected` context). 

The frontend tests will have to be changed to test the Keycloak functionality. Maybe @Piterson25 could pull this branch and put his fixes there?

Let me know if any changes have to be made, I might have missed something obvious.

### CODE REVIEW

**Review by JANKROL123 — APPROVED** [review]
wow, lots of work

**Review by Karol-2 — APPROVED** [review]
Overall looks good. One thing, I think you should add logging in as one of the initial users

Oh and one more thing, since we are using keycloak to log in, remove old LoginPage and /login path.

And a question, is it possible to change the background in the keycloak menu?

**Comment by gf-rog** [comment]
First and second point - I kept both systems in place so that you could switch between them. We could show that we understood the concept of token-based authentication by using our own implementation.
The only problem is that if a user is registered using `<RestUserProvider>` (old login system) then they can't log in using Keycloak and vice versa. I could change all initial users to be Keycloak users but then the old system couldn't be shown.
Maybe every other user should be added to Keycloak. That way you could test both systems by logging in as specific users...

Third point - The default Keycloak theme could be changed but I haven't delved into it. It's slightly more complicated than just adding your own .html file. I'll take a look at it.

**Comment by gf-rog** [comment]
I have noticed that in versions of Node above v18 the code doesn't run. I have decided to replace ts-node and nodemon with tsx and tsc-watch. The programming experience is practically the same, just using different tools.
I have also added a theme that resembles the main website. I'm not a graphic designer so any further changes should not be done by me.
All the users are added as Keycloak users since the old system is just for demonstration purposes and you could always register new users for testing.

**Review by Piterson25 — APPROVED** [review]

**Pull request merged**
