### PR TITLE
Team meetings

### PR DESCRIPTION
**Pull request by JANKROL123**

### CODE REVIEW

**Review by gf-rog — COMMENTED** [review]
There were problems while running the containers:
```
 > [frontend base 6/6] RUN npm i && npm run build:
66.96
66.96 added 509 packages, and audited 510 packages in 1m
66.96
66.96 94 packages are looking for funding
66.96   run `npm fund` for details
66.98
66.98 1 high severity vulnerability
66.98
66.98 To address all issues, run:
66.98   npm audit fix
66.98
66.98 Run `npm audit` for details.
66.98 npm notice
66.98 npm notice New major version of npm available! 9.8.1 -> 10.5.0
66.98 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.0>
66.98 npm notice Run `npm install -g npm@10.5.0` to update!
66.98 npm notice
68.32
68.32 > frontend@0.0.0 build
68.32 > tsc && vite build
68.32
85.24 src/pages/FriendsPage.tsx(17,1): error TS6133: 'Paginator' is declared but its value is never read.
85.24 src/pages/FriendsPage.tsx(26,9): error TS6133: 'friends' is declared but its value is never read.
------
failed to solve: process "/bin/sh -c npm i && npm run build" did not complete successfully: exit code: 2
```
Please run `npm audit fix` and remove the unused lines

There's a warning and `peer is null` errors if room endpoint is typed directly into the top bar.

There's an error while visiting the friends page. Only friends are stored in a Redux reducer. Why not store and fetch friends through the `UserProvider`?
```
Uncaught (in promise) Error: When called with an action of type "SET_USER_FRIENDS", the slice reducer for key "friends" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.
    Redux 2
    fetchFriends ProfilePage.tsx:50
    ProfilePage ProfilePage.tsx:53
```

The reducer is buggy - no invites are shown in the team meeting page

**Comment by gf-rog** [comment]
There is a blank page and a `socket is null` error when you create a team meeting and then go to `/profile`.
Please don't use `!` unless you are absolutely sure that a variable isn't null.
In this case, while the user is loading, the socket is null and your code ignores it. That's how you get preventable bugs.

Going to a room page directly or refreshing the room page lets you choose the camera and microphone settings and then nothing happens. It should either get you back to the meeting or redirect to another page.

Refreshing a page makes the notification disappear. Sending another invite doesn't work.
The notifications don't disappear after removing them (for example after clicking `My Profile` and back to `Notifications`).

After going to another page, Mercury spies on you and there's no way to go back to the meeting or disconnect.

Only the person that joined the team meeting's camera is visible.

**Review by Karol-2 — APPROVED** [review]

**Review by Piterson25 — APPROVED** [review]
Team meetings 💪

**Comment by gf-rog** [comment]
Notifications behave weirdly - when a notification is removed and the person in the meeting sends another one, both notifications appear.

> Going to a room page directly or refreshing the room page lets you choose the camera and microphone settings and then nothing happens. It should either get you back to the meeting or redirect to another page.

This is resolved but pressing the back button after the redirect to `/profile` still lets you go to the room page.

> After going to another page, Mercury spies on you and there's no way to go back to the meeting or disconnect.

Still not resolved. It also happens when you disconnect from the call the regular way.

After ending the meeting and starting a new one sending notifications doesn't work.

**Pull request closed without merging**
