### PR TITLE
Meetings fix + some refactoring

### PR DESCRIPTION
**Pull request by gf-rog**
Meetings are stored in the database as nodes (`(u:User)-[:IS_IN_MEETING]->(m:Meeting)`).
Meetings are first created using the "Create a meeting" button and then a friend can join it by clicking the camera button in the friends list.
You can't join if there's no meeting created or you're not a friend of the user (not tested).
The meetings are still unstable as ever...

Sockets are stored as nodes instead of attributes (`(u:User)-[:CONNECTED_TO]->(s:Socket)`).
They are created when a user is logged in and removed when the browser tab is closed.
Video call data is shared only to users which are in a meeting with a user by using socket rooms.

Chat messages are sent to all users' devices if the page is open on any of them.
The chat box scrolls down to show the newest message.

### CODE REVIEW

**Review by Piterson25 — APPROVED** [review]
Bro is a legend 🗿

**Comment by Karol-2** [comment]
A little problem:
When you create a meeting and join it, there is no way to leave. You can go to the search page, but if you try to go to a profile or friends you are still stuck in a meeting. Then the only way is to log out or edit the URL, which is not fun.

**Review by JANKROL123 — APPROVED** [review]
ok

**Comment by gf-rog** [comment]
> A little problem: When you create a meeting and join it, there is no way to leave. You can go to the search page, but if you try to go to a profile or friends you are still stuck in a meeting. Then the only way is to log out or edit the URL, which is not fun.

I agree, I'll fix it quickly

**Review by Karol-2 — APPROVED** [review]
good job

**Pull request merged**
